package com.sharkz.database.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sharkz.database.greendao.sdk.bean.TestGreenDAOJavaBean;

import com.sharkz.database.greendao.dao.TestGreenDAOJavaBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testGreenDAOJavaBeanDaoConfig;

    private final TestGreenDAOJavaBeanDao testGreenDAOJavaBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testGreenDAOJavaBeanDaoConfig = daoConfigMap.get(TestGreenDAOJavaBeanDao.class).clone();
        testGreenDAOJavaBeanDaoConfig.initIdentityScope(type);

        testGreenDAOJavaBeanDao = new TestGreenDAOJavaBeanDao(testGreenDAOJavaBeanDaoConfig, this);

        registerDao(TestGreenDAOJavaBean.class, testGreenDAOJavaBeanDao);
    }
    
    public void clear() {
        testGreenDAOJavaBeanDaoConfig.clearIdentityScope();
    }

    public TestGreenDAOJavaBeanDao getTestGreenDAOJavaBeanDao() {
        return testGreenDAOJavaBeanDao;
    }

}
